export let database = [
    {
        id: 1,
        src: '/images/MachuPicchu.png',
        country: 'Франция',
        title: 'Тур в Париж',
        subtitle: 'Романтический отдых на двоих',
        dates: '01.01.2022 - 07.01.2022',
        duration: '6 days',
        price: 600,
    },
    {
        id: 2,
        src: '/images/MachuPicchu.png',
        country: 'Франция',
        title: 'Тур в Париж',
        subtitle: 'Романтический отдых на двоих',
        dates: '01.01.2022 - 07.01.2022',
        duration: '6 days',
        price: 600,
    },
    {
        id: 3,
        src: '/images/MachuPicchu.png',
        country: 'Италия',
        title: 'Тур в Париж',
        subtitle: 'Романтический отдых на двоих',
        dates: '01.01.2022 - 07.01.2022',
        duration: '6 days',
        price: 600,
    },
    {
        id: 4,
        src: '/images/MachuPicchu.png',
        country: 'Италия',
        title: 'Тур в Париж',
        subtitle: 'Романтический отдых на двоих',
        dates: '01.01.2022 - 07.01.2022',
        duration: '6 days',
        price: 600,
    },
    {
        id: 5,
        src: '/images/MachuPicchu.png',
        country: 'Испания',
        title: 'Тур в Париж',
        subtitle: 'Романтический отдых на двоих',
        dates: '01.01.2022 - 07.01.2022',
        duration: '6 days',
        price: 600,
    },
    {
        id: 6,
        src: '/images/MachuPicchu.png',
        country: 'Испания',
        title: 'Тур в Париж',
        subtitle: 'Романтический отдых на двоих',
        dates: '01.01.2022 - 07.01.2022',
        duration: '6 days',
        price: 600,
    }
]